### Site Settings ###
title               : ASKtraining
description         : >-
                      A Generator to create a trainings plan
baseurl             : ""
theme               : minima

### Plugins ###
plugins:
  - jekyll-rdf


### RDF Database ###
#jekyll_rdf:
#  baseiri: "${base_iri}/"
#  path: "_data/${type}.ttl"
#  default_template: "default.html"
#  class_template_mappings:
#    "${base_iri}/Training": "training.html"
#    "${base_iri}/Module": "module.html"
#    "${base_iri}/Resource": "resource.html"

### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/404.html
  - pages/index.md


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
  - docker-compose.yml
  - .gitignore
  - Gemfile
